### PR TITLE
added -d flag for 'template design'

### PR DESCRIPTION
**Pull request by ty-**
-t was already taken for 'title', so I chose -d for --design.

I've included an example alternative template that uses the same style sidebar as the bootstrap docs.

Example output http://adlnet.github.io/xAPIWrapper/

### CODE REVIEW

**Comment by webpro** [comment]
Thanks for the PR! I like the option to use a different template, and I also like the template itself. However, I think it would be even more useful if the template file is just referenced from the CLI, so anybody can use any template. Otherwise, we might end up with multiple templates in this project (which is not great to maintain).

How about this:

1. we keep the option to use an alternative template file (referenced directly from CLI)
1. we add an option to use the alternative menu from within the same template (difference is probably not that big?)

Thoughts?

**Comment by ty-** [comment]
1. That sounds reasonable, but it should be clear to a user how to acquire more templates and have examples of what they look like.
2. Sure, I can see how that could add more customization. Note that I made more changes than just a sidebar in my example however. I upgraded bootstrap, removed domtastic, made some elements fixed and increased margins/paddings on some elements.

Let me know what I can do to help.

**Comment by webpro** [comment]
On second thought, I think it might be nice for users to just choose a template from the project directly. Yours is a nice example.

How about changing the option name to `-l` for `--layout`? Then I'm happy to merge it!

**Comment by webpro** [comment]
Thanks @ty-! Btw, I'm using domtastic in my template, since that's the project I originally created doxstrap for :-)

**Comment by ty-** [comment]
Thanks for merging. That was my first time seeing domtastic, I wasn't aware it was your project.

**Pull request merged**
